[project]
name = "waifuc-dataset-process"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "curl-cffi>=0.16.3",
    "hf-xet>=1.1.10",
    "onnxruntime-gpu==1.20",
    "transformers>=4.57.6",
    "waifuc[gpu]",
]

[tool.uv.sources]
waifuc = { git = "https://github.com/deepghs/waifuc.git", rev = "main" }
